version: '2'
services:
    mysql:
        container_name: "mall_mysql"
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "zyb12358"
            MYSQL_USER: 'root'
            MYSQL_PASS: 'zyb12358'
        image: "mysql:5.7" 
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
            - "./init:/docker-entrypoint-initdb.d/"
            - "./log:/var/log/mysql"
        ports:
            - "33060:3307"
